### PR TITLE
Restore request cancellation with correct implementation

### LINKED ISSUE #3063: Implement proper request cancellation
We currently have request cancellation implemented incorrectly. We are pushing the requests and their cancellation notification all in the incoming queue. Since `Thread::Queue#pop` pops items in the order in which they were pushed, we always see the cancellation _after_ we already ran the request, which completely defeats the whole purpose of cancelling it.

We tried fixing that in #2939, but it caused issues for NeoVim #3019. We need to review our understanding of what needs to happen with a cancellation and ensure it's working properly.

What we need to clarify is if a request is cancelled, what should the server return once we get to that request? Current understanding is the error code `RequestCancelled`, but maybe it shouldn't return anything and should only return that error is the request is tried? In essence, what are the expectations from the server for the first response for a cancelled request and any subsequent ones?

Relevant spec page: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#cancelRequest

### PR DESCRIPTION
**Pull request by janko**
### Motivation

Closes #3063

The project symbol search is currently slow in Zed, because it sends a `workspace/symbol` request for every new letter typed in, and attempts to cancel previous requests aren't successful, as Ruby LSP currently doesn't actually cancel requests (it enqueues `$/cancelRequest` messages instead of processing them synchronously).

### Implementation

Fix for request cancellation was already attempted in https://github.com/Shopify/ruby-lsp/issues/3063, but it caused issues with Neovim (https://github.com/Shopify/ruby-lsp/issues/3019), so it was ultimately reverted.

The problem wasn't actually in the new error responses, it was that the attempted fix contained a bug, where **it was returning a regular response *in addition to* the error response**. So, request cancellation would result in *two* responses being returned for the same request, which rightfully tripped Neovim up.

The bug was in attempting to skip the regular response using `next`. In addition to advancing iteration of nearest loop, `next` also breaks out of the nearest closure, whichever comes first. In this case, the surrounding `Mutex#synchronize` block was the nearest, so it broke out of that, and proceeded to execute `#process_message`. This resulted in regular response being sent back even if the cancelled response was previously sent.

To avoid introducing a boolean local variable, I extracted the handling logic into a method, so that I can break out using `return`.

### Automated Tests

I updated the tests to match the original implementation. However, I didn't know how to reliably assert that the 2nd response isn't getting sent, because I don't know how to wait until the worker becomes idle. I feel like I don't have enough control over the concurrency.

### Manual Tests

I tested this in Zed, and everything looked correct in the RCP message log.

### CODE REVIEW

**Comment by janko** [comment]
Maybe someone can help test this in Neovim? @adam12, @natematykiewicz, or @dzirtusss?

I think it's enough to add the following to the Gemfile:

```rb
gem "ruby-lsp", github: "janko/ruby-lsp", branch: "restore-request-cancellation"
```

**Comment by adam12** [comment]
I'll try to test this week.

**Comment by adam12** [comment]
I've observed no issues running this branch over the last few days. :+1:

File: lib/ruby_lsp/base_server.rb [hunk 1]
```diff
@@ -154,20 +154,28 @@ def fail_request_and_notify(id, message, type: Constant::MessageType::INFO)
...
-              next
-            end
-          end
+          handle_incoming_message(message)
+        end
+      end
+    end
 
-          process_message(message)
+    def handle_incoming_message(message)
```
Comment (vinistock) [inline lib/ruby_lsp/base_server.rb:163]: We're missing the sig here
```suggestion
    #: (Hash[Symbol, untyped]) -> void
    def handle_incoming_message(message)
```

Comment (janko) [reply lib/ruby_lsp/base_server.rb:163]: Added, thanks 👍🏻

**Comment by vinistock** [comment]
Good to ship once the CLA bot is happy 👍

**Comment by janko** [comment]
I have signed the CLA!

**Comment by vinistock** [comment]
Thank you for the contribution!
