### PR TITLE
Use unique IDs for registering watchers

### LINKED ISSUE #3137: Notify file events failed - Client is not running
#### VS Code Version

1.96.4

#### Ruby LSP Extension Version

0.8.20

#### Ruby LSP Server Version

0.23.6

#### Ruby LSP Add-ons

- RuboCop

#### Ruby Version

3.2.2

#### Ruby Version Manager

rbenv

#### Installed Extensions

<details>
<summary>Click to expand</summary>

- copilot (1.263.0)
- copilot-chat (0.23.2)
- debugpy (2024.14.0)
- less-aggressive-spinel-theme (0.0.3)
- markdown-preview-enhanced (0.8.15)
- ms-teams-vscode-extension (5.12.1)
- python (2024.23.2025012801)
- ruby-lsp (0.8.20)
- vscode-pylance (2025.1.102)
- vscode-yaml (1.15.0)
</details>

#### Ruby LSP Settings

<details>
<summary>Click to expand</summary>

##### Workspace

```json
{
  "formatter": "auto"
}
```

##### User

```json
{
  "enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": true,
    "definition": true,
    "workspaceSymbol": true,
    "signatureHelp": true,
    "typeHierarchy": true
  },
  "featuresConfiguration": {},
  "addonSettings": {},
  "rubyVersionManager": {
    "identifier": "auto"
  },
  "customRubyCommand": "",
  "formatter": "auto",
  "linters": null,
  "bundleGemfile": "",
  "testTimeout": 30,
  "branch": "",
  "pullDiagnosticsOn": "both",
  "useBundlerCompose": false,
  "bypassTypechecker": false,
  "rubyExecutablePath": "",
  "indexing": {},
  "erbSupport": true,
  "featureFlags": {}
}
```

</details>

### Reproduction steps

1. Restart LSP Server
2. Use autocompletion (this works fine)
3. Save file
4. I keep getting the error below and I need to restard the server

**Code snippet or error message**
```ruby
2025-02-05 09:14:03.324 [info] (MortarApp) [Error - 09:14:03] Notify file events failed.
2025-02-05 09:14:03.324 [info] (MortarApp)   Message: Client is not running
  Code: -32096 
```

### PR DESCRIPTION
**Pull request by vinistock**
### Motivation

Closes #3137

We were using the same registration ID for two different file watchers. That made VS Code override the entry, but one of them became a dangling object that didn't get appropriately cleaned up when the LSP shuts down.

Because that old file watcher was still active, the LSP client itself was not cleared either as a reference was still being held and then notifications for `didChangeWatchedFiles` were sent to a client that was already stopped, resulting in the `Notify file events failed` message.

We should always use unique IDs when registering file watchers.

### Implementation

I did 3 small things:

1. Ensured unique IDs for registering the watchers
2. Started watching `.rubocop`, which we watched before but I missed in my refactor PR
3. Started ensuring that we're only processing changes once

The last point is necessary because add-ons may register for watching the same patterns as one another or as the Ruby LSP and that results in duplicate changes being sent to the server.

The most optimal solution is #3145, but that is going to require more effort, so let's just fix the issue for now.

### Automated Tests

Added a test and verified manually that the issue is gone.

### CODE REVIEW

File: lib/ruby_lsp/server.rb [hunk 1]
```diff
@@ -301,10 +301,14 @@ def run_initialize(message)
 
       # Not every client supports dynamic registration or file watching
       if @global_state.client_capabilities.supports_watching_files
-        send_message(Request.register_watched_files(@current_request_id, "**/*.rb"))
+        send_message(Request.register_watched_files(@current_request_id, "didChangeWatchedFilesWorkspace", "**/*.rb"))
         send_message(Request.register_watched_files(
           @current_request_id,
-          Interface::RelativePattern.new(base_uri: @global_state.workspace_uri.to_s, pattern: ".rubocop.yml"),
+          "didChangeWatchedFilesRuboCopCofig",
```
Comment (andyw8) [inline lib/ruby_lsp/server.rb:307]: (typo)
```suggestion
          "didChangeWatchedFilesRuboCopConfig",
```

File: lib/ruby_lsp/server.rb [hunk 2]
```diff
@@ -301,10 +301,14 @@ def run_initialize(message)
 
       # Not every client supports dynamic registration or file watching
       if @global_state.client_capabilities.supports_watching_files
-        send_message(Request.register_watched_files(@current_request_id, "**/*.rb"))
+        send_message(Request.register_watched_files(@current_request_id, "didChangeWatchedFilesWorkspace", "**/*.rb"))
```
Comment (andyw8) [inline lib/ruby_lsp/server.rb:304]: The full name seems a little redundant since all will begin `didChangeWatchFiles`, how about `workspace` (or `:workspace`)?

Alternatively, could we auto-generate this ID, e.g. by taking a hash of the pattern argument?

**Comment by andyw8** [comment]
It probably has minimal impact, but don't know what private or under-development might be using it. Your call.

**Comment by vinistock** [comment]
Alright, I made the API compatible with the old style to avoid having to cut a breaking change just for this.

I checked every add-on published to rubygems with the `ruby-lsp` prefix and no one was using it, but better to not make unannounced breaking changes.

**Comment by andyw8** [comment]
Nice solution.
