### PR TITLE
Use URI objects instead of strings

### LINKED ISSUE #709: Error running ruby-lsp in path with spaces
When running ruby-lsp in a project with a space somewhere in the absolute path it crashes with:

```
bundler: failed to load command: ruby-lsp (/Users/tono/.asdf/installs/ruby/3.1.3/bin/ruby-lsp)
/Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/uri-0.12.1/lib/uri/rfc3986_parser.rb:66:in `split': bad URI(is not URI?): "file:///Users/tono/some/path with spaces/code" (URI::InvalidURIError)
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/uri-0.12.1/lib/uri/rfc3986_parser.rb:71:in `parse'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/uri-0.12.1/lib/uri/common.rb:193:in `parse'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/uri-0.12.1/lib/uri/common.rb:722:in `URI'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.5.1/lib/ruby_lsp/utils.rb:9:in `<module:RubyLsp>'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.5.1/lib/ruby_lsp/utils.rb:4:in `<top (required)>'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.5.1/lib/ruby_lsp/internal.rb:12:in `require'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.5.1/lib/ruby_lsp/internal.rb:12:in `<top (required)>'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.5.1/exe/ruby-lsp:21:in `require_relative'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.5.1/exe/ruby-lsp:21:in `<top (required)>'
	from /Users/tono/.asdf/installs/ruby/3.1.3/bin/ruby-lsp:25:in `load'
	from /Users/tono/.asdf/installs/ruby/3.1.3/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.4/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.4/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.4/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.4/lib/bundler/cli.rb:491:in `exec'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.4/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.4/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.4/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.4/lib/bundler/cli.rb:28:in `start'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.4/exe/bundle:45:in `block in <top (required)>'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.4/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/tono/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.4/exe/bundle:33:in `<top (required)>'
	from /Users/tono/.asdf/installs/ruby/3.1.3/bin/bundle:25:in `load'
	from /Users/tono/.asdf/installs/ruby/3.1.3/bin/bundle:25:in `<main>'
```

I am running ruby-lsp using the vscode extension.

The line from the stack trace is:
https://github.com/Shopify/ruby-lsp/blob/52193042a44f6798ad6ac35cc4dd992094d59db7/lib/ruby_lsp/utils.rb#L9

I guess the path should be url encodes here. Shall I try to submit a PR fixing this?

### PR DESCRIPTION
**Pull request by vinistock**
### Motivation

Closes #709
Closes #781

Representing URIs with strings is incorrect. We should always rely on `URI` to get the correct file paths and further we delay this change, the more entangled it might become.

There are already two issues related to this: not handling spaces properly and being unable to support unsaved files (#633).

### Implementation

The most important changes are in `Store` and `Executor`. Everything else is pretty much just adapting the types from `String` to `URI::Generic`.

One thing to note is that for unsaved files the URI is `untitled:Untitled-1`, which has path as `nil` an `opaque` as the filename (`Untitled-1`).

This is a breaking change because extensions will no longer receive a URI string, but a URI object instead.

### Automated Tests

Adapted all tests to use URI objects.

### CODE REVIEW

File: test/requests/path_completion_test.rb [hunk 1]
```diff
@@ -35,7 +35,7 @@ def test_completion_command
       @store.set(uri: @uri, source: document.source, version: 1)
       RubyLsp::Executor.new(@store, @message_queue).execute({
         method: "textDocument/completion",
-        params: { textDocument: { uri: @uri }, position: end_position },
+        params: { textDocument: { uri: @uri.to_s }, position: end_position },
```
Comment (andyw8) [inline test/requests/path_completion_test.rb:38]: (nit) Could we do the `to_s` conversion in `Executor#run` instead?

**Review by andyw8 — APPROVED** [review]

File: test/requests/path_completion_test.rb (hunk 1 above)
Comment (vinistock) [reply test/requests/path_completion_test.rb:38]: We always receive the URIs as strings from the server, so the `Executor` takes them and turns them into `URI` objects.

We end up needing both for tests, but outside of tests we would never receive a uri parameter that isn't a string, so. I don't think it's worth adding logic to handle both cases just.

Comment (andyw8) [reply test/requests/path_completion_test.rb:38]: Ah, true, it better reflects the implementation if we stick with the strings.
